package haven;

public enum GobTypes {
    TREE, BUSH, BOULDER, STUMP, LOG,

    PLAYER, ME, WHITEBITCH, GREENKIN, REDKIN, BLUEKIN, TEALKIN, YELLOWKIN, PURPLEKIN, PINKKIN,
    KNOCKED, DEAD,

    BEAST, AGGRESSIVE, CRITTER,



    OTHER;
}
